changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Breaking change
    - title: New Features 💎
      labels:
        - Feature
        - Enhancement
    - title: Fixes ⛑️
      labels:
        - Fix
        - Bug
    - title: Other Changes 🖇️
      labels:
        - "*"
