changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking change
    - title: New Features 💎
      labels:
        - enhancement
    - title: Fixes ⛑️
      labels:
        - fix
        - bug
    - title: Other Changes 🖇️
      labels:
        - "*"
