name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-test:
    name: "Unit tests"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2
          coverage: xdebug

      - name: "Install composer dependencies"
        run: composer install --prefer-dist --no-progress

      - name: "Run unit tests with coverage"
        run: composer run test:unit:coverage

      - name: SonarCloud Scan
        if: ${{ env.SONAR_TOKEN }}
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
